### ISSUE TITLE
Nice exception in Laravel 5.4

### ISSUE THREAD

**Issue by Bolandish** [ctf0/Lingo#1]
![image](https://user-images.githubusercontent.com/7235443/31538546-35afb1f6-b006-11e7-95cf-d6b7a1bfb9fe.png)

Hmm. i don't think it works in 5.4

**Comment by ctf0** [comment]
i honestly didnt test with any other than v5.5, but can u tell me what u were doing that produced this error ?

**Comment by ctf0** [comment]
closed for no feedback.

**Comment by ctf0** [comment]
**update** 

this issue is related to https://github.com/ctf0/PackageChangeLog/blob/1a8a3ee6af90b677e3e3bbca2954770713ff70a6/src/PackageChangeLogServiceProvider.php#L56 
which all it does is read your `composer.json` `scripts.post-autoload-dump` array
