### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by bajki** [ctf0/Lingo#13]
Hi, i think there is problem with this package.

If i have EN | DE | FR  translations and in FR i don't have auth.php i get this error "resources/lang/fr/auth.php): Failed to open stream: No such file or directory"

Same thing if EN auth.php has 
[
'failed' => 'These credentials do not match our records.1',
'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
]
and some other only
[
 'failed' => 'These credentials do not match our records.1',
]

Error message: "Undefined array key \"throttle\""

Thanks,
Ivan

**Comment by ctf0** [comment]
this is not an issue with the package, this is related to either the throttle mw or ur project.
