### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by mokhosh** [ctf0/Lingo#7]
i get this error when i run the composer command:
```
  include(D:\dev\aticis\resources\lang/vendor/Lingo/en/messages.php): failed to open stream: No such file or dir
  ectory


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

i also get this error with npm:
```
ERROR in ./resources/assets/js/app.js
Module not found: Error: Can't resolve '../../vendor/Lingo/js/manager' in 'D:\dev\aticis\resources\assets\js'
 @ ./resources/assets/js/app.js 3:0-40
```

**Comment by ctf0** [comment]
for the js file i think it should be `require('../vendor/Lingo/js/manager')` 
for the include issue, plz try with the latest release and reply back with ur findings.

**Comment by mokhosh** [comment]
oh that was just something i tried. i was going up one level and i thought it might help to make it two levels but no luck.
doesn't composer pull the latest release automatically?

**Comment by ctf0** [comment]
yes, but i thought u might need to uninstall and reinstall to test if the issue still persist.

for the js issue, this is what i use on my setup, however js imports are kinda wacky so u need to fiddle with it until it works.
