### ISSUE TITLE
After upgrade, the translations are no longer shown

### ISSUE THREAD

**Issue by sten** [ctf0/Lingo#8]
Hello,

First and foremost, thank you for this great library!

Everything worked well, until I updated to the latest version (1.4). I can no longer see the translations. It seems that Vue retrieves the translations correctly, because the counter is updated and correct, but nothing is filled in in the table. The following screenshot illustrates the situation:
<img width="1242" alt="screen shot 2018-07-17 at 11 16 10" src="https://user-images.githubusercontent.com/180665/42845638-e401e838-8a16-11e8-896e-def8745f2fb6.png">

I have updated the js libs using yarn, re-ran the publish step and ran `npm run watch` 
I do not see any errors in the console, and I have tried to debug the app a bit but I am not experienced in Vue.js so I am stuck. Do you have any idea what might be the issue?

Thanks a lot!

**Comment by ctf0** [comment]
i've made a demo repo https://github.com/ctf0/demos/tree/lingo, can u plz check with it 

if you can make a repo with ur setup it would be even easier to debug.

**Comment by ctf0** [comment]
you need to update the js files, because the code was refactored

**Comment by michielabe** [comment]
What do you mean by updating the js files? I've run npm run watch but that doesn't fix it.

**Comment by ctf0** [comment]
@michielabe 
> because the code was refactored

**Comment by michielabe** [comment]
So what exactly do I need to do to update the js files?

**Comment by ctf0** [comment]
force republish the assets 

https://github.com/ctf0/Lingo/blob/3d069790438a24c82f49dc7c01d3dd61d2cf3f6d/src/LingoServiceProvider.php#L34-L36

`php artisan vendor:publish --provider="ctf0\Lingo\LingoServiceProvider" --tag="assets"`

**Comment by sten** [comment]
@ctf0 I manually removed all files and republished the assets and ran `nvm run watch`. However it still did not work. It appears the published view of Lingo in `resources/views/vendor/Lingo/lingo.blade.php` was still the old version, which did not have the right routes format and broke the whole thing. So after replacing this everything works! Thanks for your help!!!

**Comment by ctf0** [comment]
@sten glad it worked but in v1.4.0 the view didnt change much 
https://github.com/ctf0/Lingo/commit/21de4b0734c67fce6ff448ae1493d5bc15ccc8e8#diff-e8edc00e0c4e38b8abe500ee7e83df7c

unless u were using an old file that didnt have the download routes, still i will update the rdme

**Comment by sten** [comment]
@ctf0 Exactly, I was missing the routes array attribute.

**Comment by ctf0** [comment]
👍
