### ISSUE TITLE
Attribute [setGroupNamespace] does not exist.

### ISSUE THREAD

**Issue by murtazamalek** [ctf0/Lingo#9]
Hi, I am trying to configure the package with Laravel 5.4 following the instructions, but I am running into an issue with the setup. 

After running the command 
`php artisan lingo:setup`

I am getting the following error:

> (1/1) InvalidArgumentException
> Attribute [setGroupNamespace] does not exist.

**Comment by ctf0** [comment]
am not sure why u r getting this, can u make a repo for me to test ?

**Comment by murtazamalek** [comment]
Sure. I have set up this repository which includes everything even the vendor folder. Please let me know if I can help you in any way.
https://github.com/murtazamalek/lingotest

**Comment by ctf0** [comment]
thanx, i will look into it and get back to you

**Comment by ctf0** [comment]
i've tested ur repo, and
- removed mongo as i dont have it
- got an error with `vendor/themsaid/laravel-langman/src/Commands/FindCommand.php` @113 (maybe because of php 7.4 🤦‍♂ ) , anyway to fix it use 
```php
: (isset($filesContent[$fileName][$languageKey][$key]) ? $filesContent[$fileName][$languageKey][$key] : '');
```

other than that, its working 
![Screen Shot 2020-01-11 at 11 41 46 AM](https://user-images.githubusercontent.com/7388088/72202404-bd465380-3467-11ea-83ba-0a66b5dd8701.png)

**Comment by murtazamalek** [comment]
I did a fresh installation of Laravel 5.4.30 and followed the instructions for installing the ctf0/lingo package. I was able to complete the installation as you've shown in the screenshot but when I try to visit the **laravel.test:8888/lingo** I am still getting the same error:
<img width="1107" alt="Screenshot 2020-01-15 at 3 57 11 PM" src="https://user-images.githubusercontent.com/5362158/72426446-b729dd00-37af-11ea-9db6-580d56918d0c.png">

I am running on PHP 7.2 just an FYI if that helps in any way.

**Comment by ctf0** [comment]
ok np, could u plz try the below on ur end and reply back

the `setGroupNamespace` is a macro on the `router` 
https://github.com/ctf0/Lingo/blob/29b3755373375d0bfeb1f8429cce444436912e4b/src/LingoServiceProvider.php#L27-L36

and called at https://github.com/ctf0/Lingo/blob/29b3755373375d0bfeb1f8429cce444436912e4b/src/LingoRoutes.php#L13

however we can get rid of it by appending the controller name `\ctf0\Lingo\Controllers` to the lines at
https://github.com/ctf0/Lingo/blob/29b3755373375d0bfeb1f8429cce444436912e4b/src/LingoRoutes.php#L16-L37

**Comment by ctf0** [comment]
maybe also try to change ` $this->app['router']->macro` with `Route::macro` and see if the problem still persist

**Comment by murtazamalek** [comment]
Yes, making that change worked for me but now I am getting error with Vue.js
`[Vue warn]: Unknown custom element: <my-notification> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

I am looking into this now.

**Comment by ctf0** [comment]
which solution worked, removing `app('router')->setGroupNamespace` ? if yes can u also try the other suggestion ?

**Comment by murtazamalek** [comment]
Removing the `app('router')->setGroupNamespace` worked but changing `$this->app['router']->macro` with `Route::macro` did not work.

**Comment by murtazamalek** [comment]
I am facing issues with the Vue.js compilation. I am currently compiling the JS with Node.js v10.x. What version of Node.js you recommend?

**Comment by ctf0** [comment]
what issues ?

**Comment by murtazamalek** [comment]
The same one I shared two days ago.
<img width="1648" alt="Screenshot 2020-01-17 at 12 27 41 PM" src="https://user-images.githubusercontent.com/5362158/72590866-c8482a80-3924-11ea-97e6-c9ee26aa15db.png">

https://github.com/ctf0/Lingo/issues/9#issuecomment-574601366

**Comment by ctf0** [comment]
have u added `require('../vendor/Lingo/js/manager')` ?

**Comment by murtazamalek** [comment]
Yes I added it and compiled the JS code.

**Comment by ctf0** [comment]
ur issues is related for vue not reading the lines at
https://github.com/ctf0/Lingo/blob/29b3755373375d0bfeb1f8429cce444436912e4b/src/resources/assets/js/manager.js#L56-L57

which is mostly a setup issue, check ur paths, vue declaration, webpack version, etc..

**Comment by murtazamalek** [comment]
If it was a path or declaration related issue, then I believe the compiler wouldn't compile the JS. Can you please provide me the Webpack and Vue.js version I should be configuring in order to make this package work?

**Comment by ctf0** [comment]
> If it was a path or declaration related issue, then I believe the compiler wouldn't compile the JS.

clearly there is an issue with ur vue setup, anyway it works correctly with latest laravel.mix which use webpack v4, and vue v2

**Comment by murtazamalek** [comment]
The issue was related to the larave-mix. Laravel 5.4.30 ships with laravel-mix 1.0 which includes Webpack 3.5.0 and so the issue was related to how the Vue component was loaded. 

I updated the line no. 56 and 57 in the `resources/assets/vendor/Lingo/js/manager.js` file:
`Vue.component('Lingo', require('./Main/container'))`
`Vue.component('MyNotification', require('vue-notif'))`
